// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/lemma": {
            "get": {
                "description": "Метод для вывода списка лемм",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "example"
                ],
                "summary": "Вывод списка лемм по запросу",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/lemma.ListResponse"
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "description": "Метод для вывода тестового сообщения",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "example"
                ],
                "summary": "ping example",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ping.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "entities.Lemma": {
            "type": "object",
            "properties": {
                "F": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "G": {
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "properties": {
                                        "V": {
                                            "type": "string",
                                            "example": "значение"
                                        }
                                    }
                                }
                            },
                            "T": {
                                "type": "string",
                                "example": "текст"
                            }
                        }
                    }
                },
                "ID": {
                    "type": "string",
                    "example": "ID леммы"
                },
                "L": {
                    "type": "object",
                    "properties": {
                        "G": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "V": {
                                        "type": "string",
                                        "example": "значение"
                                    }
                                }
                            }
                        },
                        "T": {
                            "type": "string",
                            "example": "текст леммы"
                        }
                    }
                },
                "Rev": {
                    "type": "string",
                    "example": "номер последней ревизии этой леммы"
                }
            }
        },
        "lemma.ListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.Lemma"
                    }
                }
            }
        },
        "ping.Response": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Hello"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
