definitions:
  ping.Response:
    properties:
      message:
        example: Hello
        type: string
    type: object
info:
  contact: {}
paths:
  /ping:
    get:
      consumes:
      - application/json
      description: Метод для вывода тестового сообщения
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ping.Response'
      summary: ping example
      tags:
      - example
swagger: "2.0"
