definitions:
  lemma.ListItem:
    properties:
      text:
        example: Бугульма
        type: string
    type: object
  lemma.ListResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/lemma.ListItem'
        type: array
    type: object
  test.Response:
    properties:
      message:
        example: Hello
        type: string
    type: object
info:
  contact: {}
paths:
  /lemma:
    get:
      consumes:
      - application/json
      description: Метод для вывода списка лемм
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/lemma.ListResponse'
      summary: Вывод списка лемм по запросу
      tags:
      - example
  /ping:
    get:
      consumes:
      - application/json
      description: Метод для вывода тестового сообщения
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/test.Response'
      summary: ping example
      tags:
      - example
swagger: "2.0"
