definitions:
  entities.Lemma:
    properties:
      F:
        items:
          properties:
            G:
              items:
                properties:
                  V:
                    example: вариации значений из L
                    type: string
                type: object
              type: array
            T:
              example: текст
              type: string
          type: object
        type: array
      ID:
        example: ID леммы
        type: string
      L:
        properties:
          G:
            items:
              properties:
                V:
                  example: падеж-число и прочее
                  type: string
              type: object
            type: array
          T:
            example: текст леммы
            type: string
        type: object
      Rev:
        example: номер последней ревизии этой леммы
        type: string
    type: object
  lemma.ListResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/entities.Lemma'
        type: array
    type: object
  ping.Response:
    properties:
      message:
        example: Hello
        type: string
    type: object
info:
  contact: {}
paths:
  /list:
    get:
      description: Метод для вывода списка лемм. http://opencorpora.org/dict.php?act=gram
      parameters:
      - description: Слово по которому будет поиск
        example: муха
        in: query
        name: T
        required: true
        type: string
      - description: Часть речи
        in: query
        items:
          enum:
          - Name
          - NOUN
          - ADJF
          - ADJS
          - COMP
          - VERB
          - INFN
          - PRTF
          - PRTS
          - GRND
          - NUMR
          - ADVB
          - NPRO
          - PRED
          - PREP
          - CONJ
          - PRCL
          - INTJ
          type: string
        name: V
        type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/lemma.ListResponse'
      summary: Вывод списка лемм по запросу
      tags:
      - list
  /ping:
    get:
      consumes:
      - application/json
      description: Метод для вывода тестового сообщения
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ping.Response'
      summary: ping example
      tags:
      - ping
swagger: "2.0"
